### PR TITLE
First implementation of bbob-mixint

### PR DESCRIPTION
**Pull request by ttusar**

### CODE REVIEW

**Comment by nikohansen** [comment]
Just wondering, why was this closed? Is it still worth while exploring? Which branch should I take?

**Comment by ttusar** [comment]
This is really strange. Not only I cannot recall closing the pull request, it also says that the branch has unmerged commits, which is not the case (at least as far as I can tell)...

In any case, this is the right pull request and I would appreciate your feedback.

**Comment by nikohansen** [comment]
It seems that the pull request is to go in the development branch of this https://github.com/ttusar/coco repository. Was it meant to go into https://github.com/numbbo/coco ?

**Comment by ttusar** [comment]
It should go to `numbbo/coco` eventually, sure, but I don't think it's ready yet.

**Comment by ttusar** [comment]
No, wait, I tried something from python as well (not sure anymore whether scipy's fmin or cma's fmin).

**Pull request closed without merging**
