### PR TITLE
Mario-Gan suite

### PR DESCRIPTION
**Pull request by CIGbalance**
This is my attempt at implementing the mario-gan suite. This is just intended as an update for you. I am fairly confident this should work, I have tested the evaluation script  separately. However, I cannot test the whole thing, because I cannot get the toy-socket demo to work.
- on my local computer, it does not find scipy for some reason
- on CodeOcean, I think the sockets don't really work?

If you have the time, you could tesr whether the mario stuff works for you, and revert back if it doesn't. I'll try from another computer tomorrow to see if I can get the toy-socket stuff to work there.

### CODE REVIEW

**Comment by ttusar** [comment]
I had to fix some imports, but the socket communication works for me now.

You should try it like this (pull from this branch first):
1. Go to the code-experiments/rw-problems folder and call 
````
python socket_server.py
````

This should start the socket (it should say `Server ready, listening on port 7251`)

2. In another console, go to the root directory and call
````
python do.py verbose run-c
````
This should run the example experiment on the `mario-gan` suite (with the real-world logger for now).

This fails, but you can see that the socket communication works and the failure is within the mario gan evaluation. Here is the error message (you can find it in the output of the first console):
````
python socket_server.py
Server ready, listening on port 7251
Received message: n mario-gan o 1 f 1 i 1 d 10 x 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
D:\Delo\Github\ttusar-coco\code-experiments\rw-problems\mario_gan
Error within message evaluation: invalid literal for int() with base 10: 'epoch'
Error: invalid literal for int() with base 10: 'epoch'
Traceback (most recent call last):
  File "socket_server.py", line 107, in <module>
    socket_server_start()
  File "socket_server.py", line 100, in socket_server_start
    raise e
  File "socket_server.py", line 93, in socket_server_start
    response = evaluate_message(message)
  File "socket_server.py", line 56, in evaluate_message
    raise e
  File "socket_server.py", line 48, in evaluate_message
    y = evaluate(suite_name, num_objectives, func, instance, x)
  File "D:\Delo\Github\ttusar-coco\code-experiments\rw-problems\mario_gan\mario_gan_evaluator.py", line 359, in evaluate_mario_gan
    netG, d = getNetG(prob-1, available_instances[inst-1], len(x), c, json) #-1 because COCO starts with index 1
  File "D:\Delo\Github\ttusar-coco\code-experiments\rw-problems\mario_gan\mario_gan_evaluator.py", line 336, in getNetG
    epochs = [int(str.split(file, "_")[2]) for file in files]
  File "D:\Delo\Github\ttusar-coco\code-experiments\rw-problems\mario_gan\mario_gan_evaluator.py", line 336, in <listcomp>
    epochs = [int(str.split(file, "_")[2]) for file in files]
ValueError: invalid literal for int() with base 10: 'epoch'

````

**Comment by ttusar** [comment]
Oh, and I forgot to say, if you cannot make steps 1 or 2 work, let me know which gives you troubles (and what those are).

**Comment by CIGbalance** [comment]
I cannot make the toy-socket example work on my laptop at work either, got the same problems as I had on CodeOcean. See below:

Server starts up OK:
```
$ python socket_server.py 
Server ready, listening on port 7251
```
I start the experiment in another terminal:
```
$ python do.py verbose run-c
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/c/coco.c
EXPAND	code-experiments/build/c/coco.c.in to code-experiments/build/c/coco.c
EXPAND	code-experiments/src/coco.h to code-experiments/build/c/coco.h
COPY	code-experiments/build/c/coco.c -> code-experiments/examples/bbob2009-c-cmaes/coco.c
EXPAND	code-experiments/build/c/coco.h to code-experiments/examples/bbob2009-c-cmaes/coco.h
WRITE	code-experiments/build/c/REVISION
WRITE	code-experiments/build/c/VERSION
MAKE	clean in code-experiments/build/c
CHDIR	/media/vanessa/Data/svn/teas-coco/code-experiments/build/c
COPY	Makefile.in -> Makefile
rm -f coco.o 
rm -f example_experiment.o example_experiment 

MAKE	all in code-experiments/build/c
CHDIR	/media/vanessa/Data/svn/teas-coco/code-experiments/build/c
COPY	Makefile.in -> Makefile
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment.o example_experiment.c
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o coco.o coco.c
code-experiments/src/transform_vars_permutation_helpers.c: In function ‘coco_compute_truncated_uniform_swap_permutation’:
code-experiments/src/transform_vars_permutation_helpers.c:130:64: warning: conversion to ‘long unsigned int’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
code-experiments/src/transform_vars_permutation_helpers.c:130:59: warning: conversion to ‘long int’ from ‘long unsigned int’ may change the sign of the result [-Wsign-conversion]
code-experiments/src/suite_cons_bbob_problems.c: In function ‘feasible_direction_set_length’:
code-experiments/src/suite_cons_bbob_problems.c:145:26: warning: conversion to ‘double’ from ‘size_t {aka long unsigned int}’ may alter its value [-Wconversion]
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment coco.o example_experiment.o -lm  

RUN	./example_experiment in code-experiments/build/c
ERROR: return value=1
Running the example experiment... (might take time, be patient)
COCO INFO: Results will be output to folder exdata/RS_on_bbob

COCO INFO: 12.08.19 17:47:14, d=10, running: f01.COCO FATAL ERROR: socket_communication_save_response(): Incorrect response  (size -1)
```
Then the socket fails, too:
```
$ python socket_server.py 
Server ready, listening on port 7251
Error: __exit__
Traceback (most recent call last):
  File "socket_server.py", line 107, in <module>
    socket_server_start()
  File "socket_server.py", line 100, in socket_server_start
    raise e
AttributeError: __exit__
```

**Comment by ttusar** [comment]
The error you are showing is not for the toy socket suite, but the mario gan, right?

I see I have terrible error handling and will take care of it, but what about my error above? Have you tried to fix that one and got this or do you already have problems with the code as is currently on the gbea branch?

**Comment by CIGbalance** [comment]
No, this is the code as it currently is on the gbea branch. It is trying to run RS on bbob, right? I had the same error yesterday, even before the merge.

That's why I haven't looked further into the error you had above, because I can't reproduce it at the moment, because I don't even the toy problem to work, unfortunately...

**Comment by ttusar** [comment]
Sorry, my bad. I changed the example experiment in C to work with the "mario-gan" suite by default, but forgot to also change the name of the result folder, so you couldn't have guessed this if you didn't look at the code. 

To test the working of the toy-suite, run 
````
python code-experiments/build/python/example_experiment.py toy-socket
````
That is, after you have pulled the current branch again, rebuilt the python code (`python do.py build-python`) and started the socket server. 

One other thought: which Python are you running? I'm using 3.6 and tested the toy-socket again on Windows and Ubuntu and they both work...

**Comment by CIGbalance** [comment]
Still the same issue running the python version of toy-socket as you described above.

```
python code-experiments/build/python/example_experiment.py toy-socket
COCO INFO: Results will be output to folder exdata/random_search_on_toy-socket_budget0002xD
Benchmarking solver '<function random_search' with budget=2*dimension on toy-socket suite, Tue Aug 13 11:01:09 2019
Aug13 11h01:09, d=2, running: f01COCO FATAL ERROR: socket_communication_save_response(): Incorrect response  (size -1)
```
I am running Python 2.7.15+. I'll update python and report back.

**Comment by CIGbalance** [comment]
Sockets work with Python 3.6.8!
I can reproduce the issue with mario now, so I'll fix that and do another pull request :)
I think it's fine if we drop support for Python 2.7, many packages are doing that now anyway.

**Comment by ttusar** [comment]
\o/

**Pull request merged**
